/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csx55.threads.app;

public class App {
    public static void main(String[] args) {
        // LinkedList tokens;
        // tokens = split(getMessage());
        // String result = join(tokens);
        // System.out.println(WordUtils.capitalize(result));
    }
}
