/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csx55.overlay.app;

import csx55.overlay.list.LinkedList;

import static csx55.overlay.utilities.StringUtils.join;
import static csx55.overlay.utilities.StringUtils.split;
import static csx55.overlay.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        // LinkedList tokens;
        // tokens = split(getMessage());
        // String result = join(tokens);
        // System.out.println(WordUtils.capitalize(result));
    }
}
